"""
Task 2, Step 1 -- architectural comparison.

Produces the layer-by-layer table the assignment asks for (filter sizes,
strides, output dimensions, channel counts), the depth of each network and
its trainable parameter count, for all three architectures.

The table is generated by running a dummy 32x32x3 tensor through each model
with forward hooks attached, so every number is read off the actual
implementation rather than typed by hand. If a model is edited, the table
follows automatically.

Requires no GPU and no training data -- run it before or during training.

    python compare_arch.py

Writes results/architecture_comparison.md and prints the same content.
"""

import torch
import torch.nn as nn

from config import RESULTS_DIR, MODEL_NAMES
from models import build_model


# Modules that carry weights -- used to define "depth" in the conventional
# sense (a network's depth is its number of weight layers, not its number of
# nn.Module objects: ReLU and pooling are not counted).
WEIGHT_LAYERS = (nn.Conv2d, nn.Linear)


def _fmt(value):
    """Render kernel/stride/padding tuples compactly: (3, 3) -> 3x3."""
    if value is None:
        return "-"
    if isinstance(value, (tuple, list)):
        if len(set(value)) == 1:
            return str(value[0]) if len(value) == 1 else f"{value[0]}x{value[1]}"
        return "x".join(str(v) for v in value)
    return str(value)


def trace(model: nn.Module, input_size=(1, 3, 32, 32)):
    """Run one forward pass and record every leaf module in execution order."""
    rows, handles = [], []

    def make_hook(name, module):
        def hook(_m, _inp, out):
            k = getattr(module, "kernel_size", None)
            s = getattr(module, "stride", None)
            p = getattr(module, "padding", None)
            n_params = sum(prm.numel() for prm in module.parameters(recurse=False)
                           if prm.requires_grad)
            shape = tuple(out.shape[1:])            # drop the batch dimension
            rows.append({
                "name": name,
                "type": module.__class__.__name__,
                "kernel": _fmt(k),
                "stride": _fmt(s),
                "padding": _fmt(p),
                "out": shape,
                "params": n_params,
                "is_weight_layer": isinstance(module, WEIGHT_LAYERS),
            })
        return hook

    for name, module in model.named_modules():
        if not list(module.children()):             # leaf modules only
            handles.append(module.register_forward_hook(make_hook(name, module)))

    model.eval()
    with torch.no_grad():
        model(torch.zeros(input_size))
    for h in handles:
        h.remove()
    return rows


def _shape_str(shape):
    if len(shape) == 3:
        c, h, w = shape
        return f"{h}x{w}x{c}"
    return "x".join(str(s) for s in shape)


def model_table(name: str, num_classes: int) -> str:
    model = build_model(name, num_classes)
    rows = trace(model)
    total = sum(r["params"] for r in rows)
    depth = sum(1 for r in rows if r["is_weight_layer"])
    n_conv = sum(1 for r in rows if r["type"] == "Conv2d")
    n_fc = sum(1 for r in rows if r["type"] == "Linear")

    out = [
        f"### {name}  (CIFAR-{num_classes if num_classes != 10 else 10})",
        "",
        f"Depth (weight layers): **{depth}**  ({n_conv} conv + {n_fc} fully-connected)  ",
        f"Trainable parameters: **{total:,}**",
        "",
        "| # | Layer | Type | Filter | Stride | Pad | Output (HxWxC) | Params |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for i, r in enumerate(rows, 1):
        out.append(
            f"| {i} | {r['name'] or '-'} | {r['type']} | {r['kernel']} | "
            f"{r['stride']} | {r['padding']} | {_shape_str(r['out'])} | "
            f"{r['params']:,} |"
        )
    out.append("")
    return "\n".join(out)


def summary_table() -> str:
    lines = [
        "### Summary",
        "",
        "| Network | Depth | Conv | FC | Params (CIFAR-10) | Params (CIFAR-100) | "
        "Final feature map |",
        "|---|---|---|---|---|---|---|",
    ]
    for name in MODEL_NAMES:
        m10 = build_model(name, 10)
        m100 = build_model(name, 100)
        rows = trace(m10)
        depth = sum(1 for r in rows if r["is_weight_layer"])
        n_conv = sum(1 for r in rows if r["type"] == "Conv2d")
        n_fc = sum(1 for r in rows if r["type"] == "Linear")
        p10 = sum(p.numel() for p in m10.parameters() if p.requires_grad)
        p100 = sum(p.numel() for p in m100.parameters() if p.requires_grad)
        # last 3-D output before the classifier flattens it
        spatial = [r for r in rows if len(r["out"]) == 3]
        final = _shape_str(spatial[-1]["out"]) if spatial else "-"
        lines.append(
            f"| {name} | {depth} | {n_conv} | {n_fc} | {p10:,} | {p100:,} | {final} |"
        )
    lines.append("")
    return "\n".join(lines)


def main():
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    doc = [
        "# Architecture comparison (Task 2, Step 1)",
        "",
        "All three networks take 32x32x3 input. Tables are generated directly "
        "from the implementations in `models/` by tracing a forward pass, so "
        "they reflect the code rather than the original papers' ImageNet "
        "configurations. See each model's module docstring for the "
        "adaptations made and why.",
        "",
        summary_table(),
        "---",
        "",
    ]
    for name in MODEL_NAMES:
        doc.append(model_table(name, 10))

    text = "\n".join(doc)
    (RESULTS_DIR / "architecture_comparison.md").write_text(text)
    print(text)
    print(f"-> {RESULTS_DIR / 'architecture_comparison.md'}")


if __name__ == "__main__":
    main()
